version: "3"
services:
  backend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:backend-${TIER}-latest
    volumes:
      - "${DOCKER_APP_CONFIG_FOLDER}/config.json:/server/config.json:ro"
      - "${DOCKER_APP_LOGS_FOLDER}:/server/logs"
      - "${DOCKER_APP_TMP_FOLDER}:/server/results"
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    restart: unless-stopped

  processor:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:backend-${TIER}-latest
    command: npm run start-queue-worker
    volumes:
      - "${DOCKER_APP_CONFIG_FOLDER}/config.json:/server/config.json:ro"
      - "${DOCKER_APP_LOGS_FOLDER}:/server/logs"
      - "${DOCKER_APP_TMP_FOLDER}:/server/results"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  frontend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:frontend-${TIER}-latest
    environment:
      API_HOST: http://backend:8000
    ports:
      - "80:80"
    restart: unless-stopped
