version: "3"
services:
  backend:
    image: ${BACKEND_IMAGE_LATEST}
    volumes:
      - "${APP_HOST_CONFIG_FOLDER}/config.json:/server/config.json:ro"
      - "${APP_HOST_LOGS_FOLDER}:/server/logs"
      - "${APP_HOST_TMP_FOLDER}:/server/results"
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    restart: unless-stopped

  processor:
    image: ${BACKEND_IMAGE_LATEST}
    command: npm run start-queue-worker
    volumes:
      - "${APP_HOST_CONFIG_FOLDER}/config.json:/server/config.json:ro"
      - "${APP_HOST_LOGS_FOLDER}:/server/logs"
      - "${APP_HOST_TMP_FOLDER}:/server/results"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE_LATEST}
    environment:
      API_HOST: http://backend:8000
    ports:
      - "80:80"
    restart: unless-stopped
