services:
  backend:
    build:
      context: "."
      dockerfile: "./docker/backend.dockerfile"
    volumes:
      - "./server/config.json:/server/config.json:ro"
      - "./server/logs:/server/logs"
      - "./server/results:/server/results"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: "."
      dockerfile: "./docker/frontend.dockerfile"
      args:
        APP_PATH: /spatial-power
    environment:
      API_HOST: http://backend:8000
    ports:
      - "8080:80"
