install.packages(
    c(
        'abind',
        'deldir',
        'doParallel',
        'dotCall64',
        'fields',
        'foreach',
        'goftest',
        'iterators',
        'jsonlite',
        'maps',
        'misc3d',
        'polyclip',
        'raster',
        'Rcpp',
        'sp',
        'spam',
        'sparr',
        'sparrpowR',
        'spatstat',
        'spatstat.data',
        'spatstat.utils',
        'tensor'
    ), 
    lib = .Library, 
    repos='https://cloud.r-project.org/'
)
